name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CLAZY_CHECKS: "level1"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        compiler:
          - gcc
          #- clang
        container:
          - fedora-qt5:32
    runs-on: ubuntu-latest
    container:
      image: schnitzeltony/${{ matrix.container }}
    steps:
      - name: Create install-dir
        run: |
          mkdir install

      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p build
          cd build
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            #export CXX=clang++
            export CXX=clazy
          fi
          # configure
          cmake .. \
            -DCMAKE_INSTALL_PREFIX:PATH=/usr
          # compile
          make -j $(getconf _NPROCESSORS_ONLN)
          # install
          sudo make DESTDIR=../install install

